/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ERC20NameBytes,
  ERC20NameBytesInterface,
} from "../ERC20NameBytes";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class ERC20NameBytes__factory {
  static readonly abi = _abi;
  static createInterface(): ERC20NameBytesInterface {
    return new utils.Interface(_abi) as ERC20NameBytesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC20NameBytes {
    return new Contract(address, _abi, signerOrProvider) as ERC20NameBytes;
  }
}
