/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ParticipantListLauncher,
  ParticipantListLauncherInterface,
} from "../ParticipantListLauncher";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_factory",
        type: "address",
      },
      {
        internalType: "address",
        name: "_participantListTemplate",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "participantList",
        type: "address",
      },
    ],
    name: "ListLaunched",
    type: "event",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "managers",
        type: "address[]",
      },
    ],
    name: "launchParticipantList",
    outputs: [
      {
        internalType: "address",
        name: "newList",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "participantListTemplate",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103213803806103218339818101604052604081101561003357600080fd5b508051602090910151600180546001600160a01b039384166001600160a01b031991821617909155600080549390921692169190911790556102a78061007a6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80630b64621e14610046578063c45a01551461006a578063d341c81314610072575b600080fd5b61004e610115565b604080516001600160a01b039092168252519081900360200190f35b61004e610124565b61004e6004803603602081101561008857600080fd5b8101906020810181356401000000008111156100a357600080fd5b8201836020820111156100b557600080fd5b803590602001918460208302840111640100000000831117156100d757600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600092019190915250929550610133945050505050565b6000546001600160a01b031681565b6001546001600160a01b031681565b60008054610149906001600160a01b031661021f565b604051636302262360e11b81526020600482018181528551602484015285519394506001600160a01b0385169363c6044c469387938392604490920191818601910280838360005b838110156101a9578181015183820152602001610191565b5050505090500192505050600060405180830381600087803b1580156101ce57600080fd5b505af11580156101e2573d6000803e3d6000fd5b50506040516001600160a01b03841692507fa2c24c2b6fd30a79f6f8a304395c55ba59281287136461353135de805191f49d9150600090a2919050565b6000808260601b9050604051733d602d80600a3d3981f3363d3d373d3d3d363d7360601b81528160148201526e5af43d82803e903d91602b57fd5bf360881b60288201526037816000f094935050505056fea2646970667358221220cc91d4a39422d91ebdae77bdd0600f738f5d761d3f104b30611c72815cb002bc64736f6c634300060c0033";

export class ParticipantListLauncher__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _factory: string,
    _participantListTemplate: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ParticipantListLauncher> {
    return super.deploy(
      _factory,
      _participantListTemplate,
      overrides || {}
    ) as Promise<ParticipantListLauncher>;
  }
  getDeployTransaction(
    _factory: string,
    _participantListTemplate: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      _factory,
      _participantListTemplate,
      overrides || {}
    );
  }
  attach(address: string): ParticipantListLauncher {
    return super.attach(address) as ParticipantListLauncher;
  }
  connect(signer: Signer): ParticipantListLauncher__factory {
    return super.connect(signer) as ParticipantListLauncher__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ParticipantListLauncherInterface {
    return new utils.Interface(_abi) as ParticipantListLauncherInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ParticipantListLauncher {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ParticipantListLauncher;
  }
}
