/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  SaleTemplateNameBytes,
  SaleTemplateNameBytesInterface,
} from "../SaleTemplateNameBytes";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "templateName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class SaleTemplateNameBytes__factory {
  static readonly abi = _abi;
  static createInterface(): SaleTemplateNameBytesInterface {
    return new utils.Interface(_abi) as SaleTemplateNameBytesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SaleTemplateNameBytes {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SaleTemplateNameBytes;
  }
}
