/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { EasyAuctionTemplate } from "../EasyAuctionTemplate";

export class EasyAuctionTemplate__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EasyAuctionTemplate {
    return new Contract(address, _abi, signerOrProvider) as EasyAuctionTemplate;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_WETH",
        type: "address",
      },
      {
        internalType: "address",
        name: "_auctionLauncher",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_auctionTemplateId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenOutSupply",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "minPrice",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "minBuyAmount",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "minRaise",
        type: "uint256",
      },
    ],
    name: "TemplateInitialized",
    type: "event",
  },
  {
    inputs: [],
    name: "WETH",
    outputs: [
      {
        internalType: "contract IWETH",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "auction",
    outputs: [
      {
        internalType: "contract IAuction",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "auctionLauncher",
    outputs: [
      {
        internalType: "contract IAuctionLauncher",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "auctionTemplateId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "init",
    outputs: [
      {
        internalType: "address",
        name: "newAuction",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "mesaFactory",
    outputs: [
      {
        internalType: "contract IMesaFactory",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
