/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ERC20SymbolBytes } from "../ERC20SymbolBytes";

export class ERC20SymbolBytes__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC20SymbolBytes {
    return new Contract(address, _abi, signerOrProvider) as ERC20SymbolBytes;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
