/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ParticipantListLauncher } from "../ParticipantListLauncher";

export class ParticipantListLauncher__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ParticipantListLauncher {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ParticipantListLauncher;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_factory",
        type: "address",
      },
      {
        internalType: "address",
        name: "_participantListTemplate",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "participantList",
        type: "address",
      },
    ],
    name: "ListLaunched",
    type: "event",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "managers",
        type: "address[]",
      },
    ],
    name: "launchParticipantList",
    outputs: [
      {
        internalType: "address",
        name: "newList",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "participantListTemplate",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
