/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { SaleTemplateNameBytes } from "../SaleTemplateNameBytes";

export class SaleTemplateNameBytes__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SaleTemplateNameBytes {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SaleTemplateNameBytes;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "templateName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
