/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Mintable } from "./ERC20Mintable";

export { ERC20Mintable__factory } from "./factories/ERC20Mintable__factory";
