/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ParticipantListInterface extends ethers.utils.Interface {
  functions: {
    "init(address[])": FunctionFragment;
    "initialized()": FunctionFragment;
    "isInList(address)": FunctionFragment;
    "listManagers(address)": FunctionFragment;
    "participantAmounts(address)": FunctionFragment;
    "setParticipantAmounts(address[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "init", values: [string[]]): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isInList", values: [string]): string;
  encodeFunctionData(
    functionFragment: "listManagers",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "participantAmounts",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setParticipantAmounts",
    values: [string[], BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isInList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listManagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participantAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setParticipantAmounts",
    data: BytesLike
  ): Result;

  events: {
    "AmountsUpdated(address,uint256)": EventFragment;
    "ListInitialized(address[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AmountsUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListInitialized"): EventFragment;
}

export class ParticipantList extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ParticipantListInterface;

  functions: {
    init(
      managers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialized(overrides?: CallOverrides): Promise<[boolean]>;

    isInList(account: string, overrides?: CallOverrides): Promise<[boolean]>;

    listManagers(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    participantAmounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setParticipantAmounts(
      accounts: string[],
      amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  init(
    managers: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialized(overrides?: CallOverrides): Promise<boolean>;

  isInList(account: string, overrides?: CallOverrides): Promise<boolean>;

  listManagers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  participantAmounts(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setParticipantAmounts(
    accounts: string[],
    amounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    init(managers: string[], overrides?: CallOverrides): Promise<void>;

    initialized(overrides?: CallOverrides): Promise<boolean>;

    isInList(account: string, overrides?: CallOverrides): Promise<boolean>;

    listManagers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    participantAmounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setParticipantAmounts(
      accounts: string[],
      amounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AmountsUpdated(
      account?: string | null,
      amounts?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { account: string; amounts: BigNumber }
    >;

    ListInitialized(
      managers?: null
    ): TypedEventFilter<[string[]], { managers: string[] }>;
  };

  estimateGas: {
    init(
      managers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialized(overrides?: CallOverrides): Promise<BigNumber>;

    isInList(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    listManagers(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    participantAmounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setParticipantAmounts(
      accounts: string[],
      amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    init(
      managers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isInList(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listManagers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    participantAmounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setParticipantAmounts(
      accounts: string[],
      amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
