/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface FairSaleInterface extends ethers.utils.Interface {
  functions: {
    "TEMPLATE_NAME()": FunctionFragment;
    "auctionEndDate()": FunctionFragment;
    "cancelSellOrders(bytes32[])": FunctionFragment;
    "claimFromParticipantOrder(bytes32[])": FunctionFragment;
    "clearingPriceOrder()": FunctionFragment;
    "containsOrder(bytes32)": FunctionFragment;
    "getSecondsRemainingInBatch()": FunctionFragment;
    "getUserId(address)": FunctionFragment;
    "init(bytes)": FunctionFragment;
    "initialAuctionOrder()": FunctionFragment;
    "initialized()": FunctionFragment;
    "interimOrder()": FunctionFragment;
    "interimSumBidAmount()": FunctionFragment;
    "isAtomicClosureAllowed()": FunctionFragment;
    "minFundingThreshold()": FunctionFragment;
    "minFundingThresholdNotReached()": FunctionFragment;
    "minimumBiddingAmountPerOrder()": FunctionFragment;
    "numUsers()": FunctionFragment;
    "orderCancellationEndDate()": FunctionFragment;
    "placeSellOrders(uint96[],uint96[],bytes32[])": FunctionFragment;
    "placeSellOrdersOnBehalf(uint96[],uint96[],bytes32[],address)": FunctionFragment;
    "precalculateSellAmountSum(uint256)": FunctionFragment;
    "registerUser(address)": FunctionFragment;
    "settleAuction()": FunctionFragment;
    "settleAuctionAtomically(uint96[],uint96[],bytes32[])": FunctionFragment;
    "tokenIn()": FunctionFragment;
    "tokenOut()": FunctionFragment;
    "volumeClearingPriceOrder()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "TEMPLATE_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctionEndDate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSellOrders",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromParticipantOrder",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "clearingPriceOrder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "containsOrder",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSecondsRemainingInBatch",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getUserId", values: [string]): string;
  encodeFunctionData(functionFragment: "init", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "initialAuctionOrder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interimOrder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interimSumBidAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAtomicClosureAllowed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minFundingThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minFundingThresholdNotReached",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumBiddingAmountPerOrder",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "numUsers", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "orderCancellationEndDate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "placeSellOrders",
    values: [BigNumberish[], BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "placeSellOrdersOnBehalf",
    values: [BigNumberish[], BigNumberish[], BytesLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "precalculateSellAmountSum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAuction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settleAuctionAtomically",
    values: [BigNumberish[], BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "tokenIn", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenOut", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "volumeClearingPriceOrder",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "TEMPLATE_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionEndDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSellOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromParticipantOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearingPriceOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "containsOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSecondsRemainingInBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUserId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialAuctionOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interimOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interimSumBidAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAtomicClosureAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minFundingThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minFundingThresholdNotReached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumBiddingAmountPerOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "numUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "orderCancellationEndDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "placeSellOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "placeSellOrdersOnBehalf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "precalculateSellAmountSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAuctionAtomically",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenOut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "volumeClearingPriceOrder",
    data: BytesLike
  ): Result;

  events: {
    "AuctionCleared(uint96,uint96,bytes32)": EventFragment;
    "AuctionInitialized(address,address,uint256,uint256,uint64,uint96,uint96,uint256,uint256)": EventFragment;
    "CancellationSellOrder(uint64,uint96,uint96)": EventFragment;
    "ClaimedFromOrder(uint64,uint96,uint96)": EventFragment;
    "NewSellOrder(uint64,uint96,uint96)": EventFragment;
    "NewUser(uint64,address)": EventFragment;
    "UserRegistration(address,uint64)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuctionCleared"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionInitialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancellationSellOrder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimedFromOrder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewSellOrder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewUser"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserRegistration"): EventFragment;
}

export class FairSale extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: FairSaleInterface;

  functions: {
    TEMPLATE_NAME(overrides?: CallOverrides): Promise<[string]>;

    "TEMPLATE_NAME()"(overrides?: CallOverrides): Promise<[string]>;

    auctionEndDate(overrides?: CallOverrides): Promise<[BigNumber]>;

    "auctionEndDate()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    cancelSellOrders(
      _sellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelSellOrders(bytes32[])"(
      _sellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claimFromParticipantOrder(
      orders: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimFromParticipantOrder(bytes32[])"(
      orders: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    clearingPriceOrder(overrides?: CallOverrides): Promise<[string]>;

    "clearingPriceOrder()"(overrides?: CallOverrides): Promise<[string]>;

    containsOrder(
      order: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "containsOrder(bytes32)"(
      order: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getSecondsRemainingInBatch(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getSecondsRemainingInBatch()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUserId(
      user: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "getUserId(address)"(
      user: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    init(_data: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

    "init(bytes)"(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initialAuctionOrder(overrides?: CallOverrides): Promise<[string]>;

    "initialAuctionOrder()"(overrides?: CallOverrides): Promise<[string]>;

    initialized(overrides?: CallOverrides): Promise<[boolean]>;

    "initialized()"(overrides?: CallOverrides): Promise<[boolean]>;

    interimOrder(overrides?: CallOverrides): Promise<[string]>;

    "interimOrder()"(overrides?: CallOverrides): Promise<[string]>;

    interimSumBidAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "interimSumBidAmount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    isAtomicClosureAllowed(overrides?: CallOverrides): Promise<[boolean]>;

    "isAtomicClosureAllowed()"(overrides?: CallOverrides): Promise<[boolean]>;

    minFundingThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    "minFundingThreshold()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    minFundingThresholdNotReached(
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "minFundingThresholdNotReached()"(
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    minimumBiddingAmountPerOrder(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "minimumBiddingAmountPerOrder()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    numUsers(overrides?: CallOverrides): Promise<[BigNumber]>;

    "numUsers()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    orderCancellationEndDate(overrides?: CallOverrides): Promise<[BigNumber]>;

    "orderCancellationEndDate()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    placeSellOrders(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "placeSellOrders(uint96[],uint96[],bytes32[])"(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    placeSellOrdersOnBehalf(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      orderSubmitter: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "placeSellOrdersOnBehalf(uint96[],uint96[],bytes32[],address)"(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      orderSubmitter: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    precalculateSellAmountSum(
      iterationSteps: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "precalculateSellAmountSum(uint256)"(
      iterationSteps: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registerUser(
      user: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerUser(address)"(
      user: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    settleAuction(overrides?: Overrides): Promise<ContractTransaction>;

    "settleAuction()"(overrides?: Overrides): Promise<ContractTransaction>;

    settleAuctionAtomically(
      _minBuyAmount: BigNumberish[],
      _sellAmount: BigNumberish[],
      _prevSellOrder: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "settleAuctionAtomically(uint96[],uint96[],bytes32[])"(
      _minBuyAmount: BigNumberish[],
      _sellAmount: BigNumberish[],
      _prevSellOrder: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    tokenIn(overrides?: CallOverrides): Promise<[string]>;

    "tokenIn()"(overrides?: CallOverrides): Promise<[string]>;

    tokenOut(overrides?: CallOverrides): Promise<[string]>;

    "tokenOut()"(overrides?: CallOverrides): Promise<[string]>;

    volumeClearingPriceOrder(overrides?: CallOverrides): Promise<[BigNumber]>;

    "volumeClearingPriceOrder()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  TEMPLATE_NAME(overrides?: CallOverrides): Promise<string>;

  "TEMPLATE_NAME()"(overrides?: CallOverrides): Promise<string>;

  auctionEndDate(overrides?: CallOverrides): Promise<BigNumber>;

  "auctionEndDate()"(overrides?: CallOverrides): Promise<BigNumber>;

  cancelSellOrders(
    _sellOrders: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelSellOrders(bytes32[])"(
    _sellOrders: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claimFromParticipantOrder(
    orders: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimFromParticipantOrder(bytes32[])"(
    orders: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  clearingPriceOrder(overrides?: CallOverrides): Promise<string>;

  "clearingPriceOrder()"(overrides?: CallOverrides): Promise<string>;

  containsOrder(order: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  "containsOrder(bytes32)"(
    order: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getSecondsRemainingInBatch(overrides?: CallOverrides): Promise<BigNumber>;

  "getSecondsRemainingInBatch()"(overrides?: CallOverrides): Promise<BigNumber>;

  getUserId(user: string, overrides?: Overrides): Promise<ContractTransaction>;

  "getUserId(address)"(
    user: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  init(_data: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

  "init(bytes)"(
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initialAuctionOrder(overrides?: CallOverrides): Promise<string>;

  "initialAuctionOrder()"(overrides?: CallOverrides): Promise<string>;

  initialized(overrides?: CallOverrides): Promise<boolean>;

  "initialized()"(overrides?: CallOverrides): Promise<boolean>;

  interimOrder(overrides?: CallOverrides): Promise<string>;

  "interimOrder()"(overrides?: CallOverrides): Promise<string>;

  interimSumBidAmount(overrides?: CallOverrides): Promise<BigNumber>;

  "interimSumBidAmount()"(overrides?: CallOverrides): Promise<BigNumber>;

  isAtomicClosureAllowed(overrides?: CallOverrides): Promise<boolean>;

  "isAtomicClosureAllowed()"(overrides?: CallOverrides): Promise<boolean>;

  minFundingThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  "minFundingThreshold()"(overrides?: CallOverrides): Promise<BigNumber>;

  minFundingThresholdNotReached(overrides?: CallOverrides): Promise<boolean>;

  "minFundingThresholdNotReached()"(
    overrides?: CallOverrides
  ): Promise<boolean>;

  minimumBiddingAmountPerOrder(overrides?: CallOverrides): Promise<BigNumber>;

  "minimumBiddingAmountPerOrder()"(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  numUsers(overrides?: CallOverrides): Promise<BigNumber>;

  "numUsers()"(overrides?: CallOverrides): Promise<BigNumber>;

  orderCancellationEndDate(overrides?: CallOverrides): Promise<BigNumber>;

  "orderCancellationEndDate()"(overrides?: CallOverrides): Promise<BigNumber>;

  placeSellOrders(
    _minBuyAmounts: BigNumberish[],
    _sellAmounts: BigNumberish[],
    _prevSellOrders: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "placeSellOrders(uint96[],uint96[],bytes32[])"(
    _minBuyAmounts: BigNumberish[],
    _sellAmounts: BigNumberish[],
    _prevSellOrders: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  placeSellOrdersOnBehalf(
    _minBuyAmounts: BigNumberish[],
    _sellAmounts: BigNumberish[],
    _prevSellOrders: BytesLike[],
    orderSubmitter: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "placeSellOrdersOnBehalf(uint96[],uint96[],bytes32[],address)"(
    _minBuyAmounts: BigNumberish[],
    _sellAmounts: BigNumberish[],
    _prevSellOrders: BytesLike[],
    orderSubmitter: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  precalculateSellAmountSum(
    iterationSteps: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "precalculateSellAmountSum(uint256)"(
    iterationSteps: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registerUser(
    user: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerUser(address)"(
    user: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  settleAuction(overrides?: Overrides): Promise<ContractTransaction>;

  "settleAuction()"(overrides?: Overrides): Promise<ContractTransaction>;

  settleAuctionAtomically(
    _minBuyAmount: BigNumberish[],
    _sellAmount: BigNumberish[],
    _prevSellOrder: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "settleAuctionAtomically(uint96[],uint96[],bytes32[])"(
    _minBuyAmount: BigNumberish[],
    _sellAmount: BigNumberish[],
    _prevSellOrder: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  tokenIn(overrides?: CallOverrides): Promise<string>;

  "tokenIn()"(overrides?: CallOverrides): Promise<string>;

  tokenOut(overrides?: CallOverrides): Promise<string>;

  "tokenOut()"(overrides?: CallOverrides): Promise<string>;

  volumeClearingPriceOrder(overrides?: CallOverrides): Promise<BigNumber>;

  "volumeClearingPriceOrder()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    TEMPLATE_NAME(overrides?: CallOverrides): Promise<string>;

    "TEMPLATE_NAME()"(overrides?: CallOverrides): Promise<string>;

    auctionEndDate(overrides?: CallOverrides): Promise<BigNumber>;

    "auctionEndDate()"(overrides?: CallOverrides): Promise<BigNumber>;

    cancelSellOrders(
      _sellOrders: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelSellOrders(bytes32[])"(
      _sellOrders: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    claimFromParticipantOrder(
      orders: BytesLike[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        sumTokenOutAmount: BigNumber;
        sumTokenInAmount: BigNumber;
      }
    >;

    "claimFromParticipantOrder(bytes32[])"(
      orders: BytesLike[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        sumTokenOutAmount: BigNumber;
        sumTokenInAmount: BigNumber;
      }
    >;

    clearingPriceOrder(overrides?: CallOverrides): Promise<string>;

    "clearingPriceOrder()"(overrides?: CallOverrides): Promise<string>;

    containsOrder(
      order: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "containsOrder(bytes32)"(
      order: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getSecondsRemainingInBatch(overrides?: CallOverrides): Promise<BigNumber>;

    "getSecondsRemainingInBatch()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserId(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getUserId(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    init(_data: BytesLike, overrides?: CallOverrides): Promise<void>;

    "init(bytes)"(_data: BytesLike, overrides?: CallOverrides): Promise<void>;

    initialAuctionOrder(overrides?: CallOverrides): Promise<string>;

    "initialAuctionOrder()"(overrides?: CallOverrides): Promise<string>;

    initialized(overrides?: CallOverrides): Promise<boolean>;

    "initialized()"(overrides?: CallOverrides): Promise<boolean>;

    interimOrder(overrides?: CallOverrides): Promise<string>;

    "interimOrder()"(overrides?: CallOverrides): Promise<string>;

    interimSumBidAmount(overrides?: CallOverrides): Promise<BigNumber>;

    "interimSumBidAmount()"(overrides?: CallOverrides): Promise<BigNumber>;

    isAtomicClosureAllowed(overrides?: CallOverrides): Promise<boolean>;

    "isAtomicClosureAllowed()"(overrides?: CallOverrides): Promise<boolean>;

    minFundingThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    "minFundingThreshold()"(overrides?: CallOverrides): Promise<BigNumber>;

    minFundingThresholdNotReached(overrides?: CallOverrides): Promise<boolean>;

    "minFundingThresholdNotReached()"(
      overrides?: CallOverrides
    ): Promise<boolean>;

    minimumBiddingAmountPerOrder(overrides?: CallOverrides): Promise<BigNumber>;

    "minimumBiddingAmountPerOrder()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numUsers(overrides?: CallOverrides): Promise<BigNumber>;

    "numUsers()"(overrides?: CallOverrides): Promise<BigNumber>;

    orderCancellationEndDate(overrides?: CallOverrides): Promise<BigNumber>;

    "orderCancellationEndDate()"(overrides?: CallOverrides): Promise<BigNumber>;

    placeSellOrders(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "placeSellOrders(uint96[],uint96[],bytes32[])"(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    placeSellOrdersOnBehalf(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      orderSubmitter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "placeSellOrdersOnBehalf(uint96[],uint96[],bytes32[],address)"(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      orderSubmitter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    precalculateSellAmountSum(
      iterationSteps: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "precalculateSellAmountSum(uint256)"(
      iterationSteps: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    registerUser(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "registerUser(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    settleAuction(overrides?: CallOverrides): Promise<string>;

    "settleAuction()"(overrides?: CallOverrides): Promise<string>;

    settleAuctionAtomically(
      _minBuyAmount: BigNumberish[],
      _sellAmount: BigNumberish[],
      _prevSellOrder: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "settleAuctionAtomically(uint96[],uint96[],bytes32[])"(
      _minBuyAmount: BigNumberish[],
      _sellAmount: BigNumberish[],
      _prevSellOrder: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    tokenIn(overrides?: CallOverrides): Promise<string>;

    "tokenIn()"(overrides?: CallOverrides): Promise<string>;

    tokenOut(overrides?: CallOverrides): Promise<string>;

    "tokenOut()"(overrides?: CallOverrides): Promise<string>;

    volumeClearingPriceOrder(overrides?: CallOverrides): Promise<BigNumber>;

    "volumeClearingPriceOrder()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    AuctionCleared(
      soldTokenOuts: null,
      soldTokenIns: null,
      clearingPriceOrder: null
    ): EventFilter;

    AuctionInitialized(
      tokenOut: string | null,
      tokenIn: string | null,
      orderCancellationEndDate: null,
      auctionEndDate: null,
      userId: null,
      auctionedSellAmount: null,
      minBuyAmount: null,
      minimumBiddingAmountPerOrder: null,
      minFundingThreshold: null
    ): EventFilter;

    CancellationSellOrder(
      userId: BigNumberish | null,
      buyAmount: null,
      sellAmount: null
    ): EventFilter;

    ClaimedFromOrder(
      userId: BigNumberish | null,
      buyAmount: null,
      sellAmount: null
    ): EventFilter;

    NewSellOrder(
      userId: BigNumberish | null,
      buyAmount: null,
      sellAmount: null
    ): EventFilter;

    NewUser(
      userId: BigNumberish | null,
      userAddress: string | null
    ): EventFilter;

    UserRegistration(user: string | null, userId: null): EventFilter;
  };

  estimateGas: {
    TEMPLATE_NAME(overrides?: CallOverrides): Promise<BigNumber>;

    "TEMPLATE_NAME()"(overrides?: CallOverrides): Promise<BigNumber>;

    auctionEndDate(overrides?: CallOverrides): Promise<BigNumber>;

    "auctionEndDate()"(overrides?: CallOverrides): Promise<BigNumber>;

    cancelSellOrders(
      _sellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelSellOrders(bytes32[])"(
      _sellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    claimFromParticipantOrder(
      orders: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claimFromParticipantOrder(bytes32[])"(
      orders: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    clearingPriceOrder(overrides?: CallOverrides): Promise<BigNumber>;

    "clearingPriceOrder()"(overrides?: CallOverrides): Promise<BigNumber>;

    containsOrder(
      order: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "containsOrder(bytes32)"(
      order: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSecondsRemainingInBatch(overrides?: CallOverrides): Promise<BigNumber>;

    "getSecondsRemainingInBatch()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserId(user: string, overrides?: Overrides): Promise<BigNumber>;

    "getUserId(address)"(
      user: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    init(_data: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "init(bytes)"(_data: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    initialAuctionOrder(overrides?: CallOverrides): Promise<BigNumber>;

    "initialAuctionOrder()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialized(overrides?: CallOverrides): Promise<BigNumber>;

    "initialized()"(overrides?: CallOverrides): Promise<BigNumber>;

    interimOrder(overrides?: CallOverrides): Promise<BigNumber>;

    "interimOrder()"(overrides?: CallOverrides): Promise<BigNumber>;

    interimSumBidAmount(overrides?: CallOverrides): Promise<BigNumber>;

    "interimSumBidAmount()"(overrides?: CallOverrides): Promise<BigNumber>;

    isAtomicClosureAllowed(overrides?: CallOverrides): Promise<BigNumber>;

    "isAtomicClosureAllowed()"(overrides?: CallOverrides): Promise<BigNumber>;

    minFundingThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    "minFundingThreshold()"(overrides?: CallOverrides): Promise<BigNumber>;

    minFundingThresholdNotReached(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "minFundingThresholdNotReached()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minimumBiddingAmountPerOrder(overrides?: CallOverrides): Promise<BigNumber>;

    "minimumBiddingAmountPerOrder()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numUsers(overrides?: CallOverrides): Promise<BigNumber>;

    "numUsers()"(overrides?: CallOverrides): Promise<BigNumber>;

    orderCancellationEndDate(overrides?: CallOverrides): Promise<BigNumber>;

    "orderCancellationEndDate()"(overrides?: CallOverrides): Promise<BigNumber>;

    placeSellOrders(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "placeSellOrders(uint96[],uint96[],bytes32[])"(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    placeSellOrdersOnBehalf(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      orderSubmitter: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "placeSellOrdersOnBehalf(uint96[],uint96[],bytes32[],address)"(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      orderSubmitter: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    precalculateSellAmountSum(
      iterationSteps: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "precalculateSellAmountSum(uint256)"(
      iterationSteps: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    registerUser(user: string, overrides?: Overrides): Promise<BigNumber>;

    "registerUser(address)"(
      user: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    settleAuction(overrides?: Overrides): Promise<BigNumber>;

    "settleAuction()"(overrides?: Overrides): Promise<BigNumber>;

    settleAuctionAtomically(
      _minBuyAmount: BigNumberish[],
      _sellAmount: BigNumberish[],
      _prevSellOrder: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "settleAuctionAtomically(uint96[],uint96[],bytes32[])"(
      _minBuyAmount: BigNumberish[],
      _sellAmount: BigNumberish[],
      _prevSellOrder: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    tokenIn(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenIn()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokenOut(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenOut()"(overrides?: CallOverrides): Promise<BigNumber>;

    volumeClearingPriceOrder(overrides?: CallOverrides): Promise<BigNumber>;

    "volumeClearingPriceOrder()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    TEMPLATE_NAME(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "TEMPLATE_NAME()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    auctionEndDate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "auctionEndDate()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelSellOrders(
      _sellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelSellOrders(bytes32[])"(
      _sellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claimFromParticipantOrder(
      orders: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimFromParticipantOrder(bytes32[])"(
      orders: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    clearingPriceOrder(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "clearingPriceOrder()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    containsOrder(
      order: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "containsOrder(bytes32)"(
      order: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSecondsRemainingInBatch(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSecondsRemainingInBatch()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserId(
      user: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "getUserId(address)"(
      user: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    init(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "init(bytes)"(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initialAuctionOrder(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "initialAuctionOrder()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "initialized()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    interimOrder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "interimOrder()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    interimSumBidAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "interimSumBidAmount()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAtomicClosureAllowed(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isAtomicClosureAllowed()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minFundingThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "minFundingThreshold()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minFundingThresholdNotReached(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "minFundingThresholdNotReached()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minimumBiddingAmountPerOrder(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "minimumBiddingAmountPerOrder()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numUsers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "numUsers()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    orderCancellationEndDate(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "orderCancellationEndDate()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    placeSellOrders(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "placeSellOrders(uint96[],uint96[],bytes32[])"(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    placeSellOrdersOnBehalf(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      orderSubmitter: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "placeSellOrdersOnBehalf(uint96[],uint96[],bytes32[],address)"(
      _minBuyAmounts: BigNumberish[],
      _sellAmounts: BigNumberish[],
      _prevSellOrders: BytesLike[],
      orderSubmitter: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    precalculateSellAmountSum(
      iterationSteps: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "precalculateSellAmountSum(uint256)"(
      iterationSteps: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registerUser(
      user: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerUser(address)"(
      user: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    settleAuction(overrides?: Overrides): Promise<PopulatedTransaction>;

    "settleAuction()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    settleAuctionAtomically(
      _minBuyAmount: BigNumberish[],
      _sellAmount: BigNumberish[],
      _prevSellOrder: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "settleAuctionAtomically(uint96[],uint96[],bytes32[])"(
      _minBuyAmount: BigNumberish[],
      _sellAmount: BigNumberish[],
      _prevSellOrder: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    tokenIn(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tokenIn()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenOut(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tokenOut()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    volumeClearingPriceOrder(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "volumeClearingPriceOrder()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
