/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EasyAuction } from "./EasyAuction";
export type { ERC20 } from "./ERC20";
export type { ERC20NameBytes } from "./ERC20NameBytes";
export type { ERC20SymbolBytes } from "./ERC20SymbolBytes";

export { EasyAuction__factory } from "./factories/EasyAuction__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { ERC20NameBytes__factory } from "./factories/ERC20NameBytes__factory";
export { ERC20SymbolBytes__factory } from "./factories/ERC20SymbolBytes__factory";
