/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface FixedPriceSaleTemplateInterface extends ethers.utils.Interface {
  functions: {
    "createSale()": FunctionFragment;
    "init(bytes)": FunctionFragment;
    "mesaFactory()": FunctionFragment;
    "saleLauncher()": FunctionFragment;
    "saleTemplateId()": FunctionFragment;
    "templateName()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createSale",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "init", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "mesaFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "saleLauncher",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "saleTemplateId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "templateName",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "createSale", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mesaFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "saleLauncher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "saleTemplateId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "templateName",
    data: BytesLike
  ): Result;

  events: {
    "TemplateInitialized(address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TemplateInitialized"): EventFragment;
}

export class FixedPriceSaleTemplate extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: FixedPriceSaleTemplateInterface;

  functions: {
    createSale(overrides?: PayableOverrides): Promise<ContractTransaction>;

    "createSale()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

    init(_data: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

    "init(bytes)"(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    mesaFactory(overrides?: CallOverrides): Promise<[string]>;

    "mesaFactory()"(overrides?: CallOverrides): Promise<[string]>;

    saleLauncher(overrides?: CallOverrides): Promise<[string]>;

    "saleLauncher()"(overrides?: CallOverrides): Promise<[string]>;

    saleTemplateId(overrides?: CallOverrides): Promise<[BigNumber]>;

    "saleTemplateId()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    templateName(overrides?: CallOverrides): Promise<[string]>;

    "templateName()"(overrides?: CallOverrides): Promise<[string]>;
  };

  createSale(overrides?: PayableOverrides): Promise<ContractTransaction>;

  "createSale()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

  init(_data: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

  "init(bytes)"(
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  mesaFactory(overrides?: CallOverrides): Promise<string>;

  "mesaFactory()"(overrides?: CallOverrides): Promise<string>;

  saleLauncher(overrides?: CallOverrides): Promise<string>;

  "saleLauncher()"(overrides?: CallOverrides): Promise<string>;

  saleTemplateId(overrides?: CallOverrides): Promise<BigNumber>;

  "saleTemplateId()"(overrides?: CallOverrides): Promise<BigNumber>;

  templateName(overrides?: CallOverrides): Promise<string>;

  "templateName()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createSale(overrides?: CallOverrides): Promise<string>;

    "createSale()"(overrides?: CallOverrides): Promise<string>;

    init(_data: BytesLike, overrides?: CallOverrides): Promise<void>;

    "init(bytes)"(_data: BytesLike, overrides?: CallOverrides): Promise<void>;

    mesaFactory(overrides?: CallOverrides): Promise<string>;

    "mesaFactory()"(overrides?: CallOverrides): Promise<string>;

    saleLauncher(overrides?: CallOverrides): Promise<string>;

    "saleLauncher()"(overrides?: CallOverrides): Promise<string>;

    saleTemplateId(overrides?: CallOverrides): Promise<BigNumber>;

    "saleTemplateId()"(overrides?: CallOverrides): Promise<BigNumber>;

    templateName(overrides?: CallOverrides): Promise<string>;

    "templateName()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    TemplateInitialized(
      tokenOut: null,
      tokenIn: null,
      tokenPrice: null,
      tokensForSale: null,
      startDate: null,
      endDate: null,
      allocationMin: null,
      allocationMax: null,
      minimumRaise: null,
      owner: null
    ): EventFilter;
  };

  estimateGas: {
    createSale(overrides?: PayableOverrides): Promise<BigNumber>;

    "createSale()"(overrides?: PayableOverrides): Promise<BigNumber>;

    init(_data: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "init(bytes)"(_data: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    mesaFactory(overrides?: CallOverrides): Promise<BigNumber>;

    "mesaFactory()"(overrides?: CallOverrides): Promise<BigNumber>;

    saleLauncher(overrides?: CallOverrides): Promise<BigNumber>;

    "saleLauncher()"(overrides?: CallOverrides): Promise<BigNumber>;

    saleTemplateId(overrides?: CallOverrides): Promise<BigNumber>;

    "saleTemplateId()"(overrides?: CallOverrides): Promise<BigNumber>;

    templateName(overrides?: CallOverrides): Promise<BigNumber>;

    "templateName()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createSale(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    "createSale()"(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    init(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "init(bytes)"(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    mesaFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "mesaFactory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    saleLauncher(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "saleLauncher()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    saleTemplateId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "saleTemplateId()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    templateName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "templateName()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
