/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ParticipantListLauncherInterface extends ethers.utils.Interface {
  functions: {
    "factory()": FunctionFragment;
    "launchParticipantList(address[])": FunctionFragment;
    "participantListTemplate()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "launchParticipantList",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "participantListTemplate",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "launchParticipantList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participantListTemplate",
    data: BytesLike
  ): Result;

  events: {
    "ListLaunched(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ListLaunched"): EventFragment;
}

export class ParticipantListLauncher extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ParticipantListLauncherInterface;

  functions: {
    factory(overrides?: CallOverrides): Promise<[string]>;

    "factory()"(overrides?: CallOverrides): Promise<[string]>;

    launchParticipantList(
      managers: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "launchParticipantList(address[])"(
      managers: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    participantListTemplate(overrides?: CallOverrides): Promise<[string]>;

    "participantListTemplate()"(overrides?: CallOverrides): Promise<[string]>;
  };

  factory(overrides?: CallOverrides): Promise<string>;

  "factory()"(overrides?: CallOverrides): Promise<string>;

  launchParticipantList(
    managers: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "launchParticipantList(address[])"(
    managers: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  participantListTemplate(overrides?: CallOverrides): Promise<string>;

  "participantListTemplate()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    factory(overrides?: CallOverrides): Promise<string>;

    "factory()"(overrides?: CallOverrides): Promise<string>;

    launchParticipantList(
      managers: string[],
      overrides?: CallOverrides
    ): Promise<string>;

    "launchParticipantList(address[])"(
      managers: string[],
      overrides?: CallOverrides
    ): Promise<string>;

    participantListTemplate(overrides?: CallOverrides): Promise<string>;

    "participantListTemplate()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    ListLaunched(participantList: string | null): EventFilter;
  };

  estimateGas: {
    factory(overrides?: CallOverrides): Promise<BigNumber>;

    "factory()"(overrides?: CallOverrides): Promise<BigNumber>;

    launchParticipantList(
      managers: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "launchParticipantList(address[])"(
      managers: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    participantListTemplate(overrides?: CallOverrides): Promise<BigNumber>;

    "participantListTemplate()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    launchParticipantList(
      managers: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "launchParticipantList(address[])"(
      managers: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    participantListTemplate(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "participantListTemplate()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
